### ISSUE TITLE
ROS2 support

### ISSUE THREAD

**Issue by BRoboticsSHADO** [ros-perception/imu_pipeline#16]
Hi

Is there any release / support on imu_pipeline in ROS2?

Best,
Samuel

**Comment by tonybaltovski** [comment]
There is no ROS2 support currently.  Pull requests are welcome.

**Comment by mikeferguson** [comment]
I'm assigning this to myself - I've got a couple PRs open - one more in process (to add components for the imu_transformers package) and then this would be fully functional in ROS 2

**Comment by mikeferguson** [comment]
Last PR before a release: https://github.com/ros-perception/imu_pipeline/pull/21

**Comment by mikeferguson** [comment]
0.4.0 tagged as first release to ROS2 - request for release repo created: https://github.com/ros2-gbp/ros2-gbp-github-org/pull/405

**Comment by mikeferguson** [comment]
0.4.1 in:

- Rolling: https://github.com/ros/rosdistro/pull/39443
- Iron: https://github.com/ros/rosdistro/pull/39444
- Humble: https://github.com/ros/rosdistro/pull/39445
