### ISSUE TITLE
New imu_pipeline release 

### ISSUE THREAD

**Issue by ahcorde** [ros-perception/imu_pipeline#24]
@mikeferguson Do you mind to release a new version ? CI is failing https://build.ros2.org/view/Rbin_uJ64/job/Rbin_uJ64__imu_transformer__ubuntu_jammy_amd64__binary/4/consoleFull

**Comment by mikeferguson** [comment]
Yep - looks like I fixed the deprecation warning last month, and the header just got removed from rolling.

**Comment by mikeferguson** [comment]
https://github.com/ros/rosdistro/pull/39856
